"""Protocols shared by the real device and test doubles."""

from __future__ import annotations

from typing import Protocol

from PIL import Image


class DeckInterface(Protocol):
    def __enter__(self) -> "DeckInterface": ...

    def __exit__(self, *_: object) -> None: ...

    def set_brightness(self, percent: int) -> bool: ...

    def set_key_image(self, key: int, image: Image.Image) -> bool: ...

    def set_key_jpeg(self, key: int, data: bytes) -> bool: ...

    def clear_all(self) -> None: ...

    def read(self, timeout_ms: int = 100) -> bytes: ...

    def close(self) -> None: ...
